version: '3.8'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: codcerto-api
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: codcerto-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    env_file:
      - .env


